default_install_hook_types: [pre-commit]
default_stages: [pre-commit]

repos:
  - repo: builtin
    hooks:
      - id: fix-byte-order-marker

  - repo: local
    hooks:
      - id: oxfmt
        name: oxfmt
        entry: bun run fmt:staged
        language: system
        require_serial: true
